### ISSUE TITLE
Dharamsitejas: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by tjdharamsi** [JaredHawkins/TweetCurator#1]
This project is something I can relate it to my previous project at the school which was on " Maintaining Relevance of a Data Lake". This would help me speed up the task.  I have done courses and projects in Python, Data Mining, Web Technologies and Mongo.<p><br><blockquote>This issue was created by @Dharamsitejas via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by JaredHawkins** [comment]
Hi Tejas - welcome to the project!  I'm going to follow-up with you via email.
